<?php
if(isset($_POST["s"])){
    require 'vendor/autoload.php';
    $authenticator = new PHPGangsta_GoogleAuthenticator();
    $secret = $authenticator->createSecret();
    echo "Secret: ".$secret;


    $secret = 'PQ3HQXIADIERWMAH'; //This is used to generate QR code
    $otp = $_POST["n"] ;//Generated by Authenticator.

    $tolerance = 0;

    $checkResult = $authenticator->verifyCode($secret, $otp, $tolerance);

    if ($checkResult)
    {
        echo '<br>OTP is Validated Succesfully';

    } else {
        echo '<br>FAILED<br><br>';
    }

    $cht = "qr";
    // CHart Size
    $chs = "300x300";

    // default: UTF-8
    $choe = "UTF-8";
    $qrcode = 'https://chart.googleapis.com/chart?cht=' . $cht . '&chs=' . $chs . '&chl=' . $secret . '&choe=' . $choe;
    $qrcode = 'https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/Example%3Aalice%40google.com%3Fsecret%' . $secret . '%26issuer%3DExample';
    echo "<img src=". $qrcode ." alt='Secret key'>";
}
?>
<form method="post">
  <input type="text" name="n">
  <input type="submit" name="s">
</form>
